# Simple package

name: usd
parent: default

matches:
  - trigger: ":usd"
    trim: true
    replace: "{{output}}"
    vars:
    - name: output
      type: script
      params:
        args:
          - python
          - "%PACKAGES%/usd/usd.py"
