# Simple package

name: usd
parent: default

matches:
  - trigger: ":usd"
    trim: true
    replace: "{{output}}"
    vars:
    - name: output
      type: script
      params:
        args:
          - python3
          - "%PACKAGES%/usd/usd.py"

  - trigger: "#blue"
    trim: true
    replace: "{{blue}}"
    vars:
    - name: blue
      type: script
      params:
        args:
          - python3
          - "%PACKAGES%/usd/usd.py"
          - "--option=blue-average"

